const runtime = require("./src/index");

module.exports = {
  plugin_id: "kcloud_data_sharing",
  name: "KCloud Data Sharing",
  command_entrypoint: "plugins/kcloud_data_sharing/bootstrap.js",
  runtime_entrypoint: "plugins/kcloud_data_sharing/bootstrap.js",
  kcloudDataSharing: runtime.kcloudDataSharing,
  command: runtime.kcloudDataSharing,
  runtime,
  buildKcloudDataSharingStatusReport: runtime.buildKcloudStatusReport,
  buildKcloudDataSharingInitReport: runtime.initKcloudConfig,
  buildKcloudDataSharingQueueOutboxReport: runtime.queueOutboxEvent,
  buildKcloudDataSharingQueueInboxReport: runtime.queueInboxEvent,
  buildKcloudDataSharingEventInspectionReport: runtime.inspectKcloudEvents,
  buildKcloudDataSharingOutboxStatusReport: runtime.buildKcloudOutboxReport,
  buildKcloudDataSharingInboxStatusReport: runtime.buildKcloudInboxReport,
  buildKcloudDataSharingTransmitReport: runtime.buildKcloudTransmitReport,
  buildKcloudDataSharingReceiveReport: runtime.buildKcloudReceiveReport,
  buildKcloudDataSharingAuditReport: runtime.buildKcloudAuditReport,
  buildKcloudDataSharingReadinessReport: runtime.buildKcloudReadinessReport,
  readKcloudOutbox: runtime.readOutbox,
  readKcloudInbox: runtime.readInbox,
  readKcloudAckLog: runtime.readAckLog,
  readKcloudDeadLetter: runtime.readDeadLetter,
  readKcloudSyncCursor: runtime.readSyncCursor,
  updateKcloudEventStatus: runtime.updateEventStatus,
  moveKcloudEventToDeadLetter: runtime.moveEventToDeadLetter,
  appendKcloudAckLog: runtime.appendKcloudAckLog,
  updateKcloudSyncCursor: runtime.updateSyncCursor,
  hashKcloudPayload: runtime.hashPayload,
  createKcloudCloudClient: runtime.createKcloudCloudClient,
  transmitKcloudEvent: runtime.transmitOneEvent,
  transmitKcloudEvents: runtime.transmitPendingEvents,
  receiveKcloudEvent: runtime.receiveOneEvent,
  receiveKcloudEvents: runtime.receiveCloudEvents,
  syncKcloudDataSharing: runtime.synchronizeKcloud,
  renderKcloudDataSharingReport: runtime.renderKcloudReport
};
