const runtime = require("./runtime");

module.exports = {
  plugin_id: "ai_tool_adapters",
  name: "AI Tool Adapter",
  command_entrypoint: "plugins/ai_tool_adapters/runtime/index.js",
  runtime_entrypoint: "plugins/ai_tool_adapters/runtime/index.js",
  provider: runtime.provider,
  getProviderInfo: runtime.getProviderInfo,
  ensureState: runtime.ensureState,
  listAvailableTools: runtime.listAvailableTools,
  getToolCapabilities: runtime.getToolCapabilities,
  canRunContract: runtime.canRunContract,
  runContract: runtime.runContract,
  getRunEvidence: runtime.getRunEvidence,
  buildAdapterProviderReport: runtime.buildAdapterProviderReport,
  buildRunReportFromContract: runtime.buildRunReportFromContract,
  aiToolAdapters: runtime.aiToolAdapters,
  getPluginStatus: runtime.getPluginStatus,
  buildAiToolAdaptersStatus: runtime.buildAiToolAdaptersStatus,
  buildAiToolAdaptersScanReport: runtime.buildAiToolAdaptersScanReport,
  buildAiToolAdaptersCatalogReport: runtime.buildAiToolAdaptersCatalogReport,
  buildAiToolAdaptersAdaptationPackReport: runtime.buildAiToolAdaptersAdaptationPackReport,
  buildAiToolAdaptersPromptCatalogReport: runtime.buildAiToolAdaptersPromptCatalogReport,
  buildAiToolAdaptersPromptCompositionReport: runtime.buildAiToolAdaptersPromptCompositionReport,
  buildAiToolAdaptersPromptBlueprintReport: runtime.buildAiToolAdaptersPromptBlueprintReport,
  buildAiToolAdaptersListReport: runtime.buildAiToolAdaptersListReport,
  buildAiToolAdaptersShowReport: runtime.buildAiToolAdaptersShowReport,
  buildAiToolAdaptersRegisterReport: runtime.buildAiToolAdaptersRegisterReport,
  buildAiToolAdaptersUnregisterReport: runtime.buildAiToolAdaptersUnregisterReport,
  buildAiToolAdaptersTestReport: runtime.buildAiToolAdaptersTestReport,
  buildAiToolAdaptersRunContractReport: runtime.buildAiToolAdaptersRunContractReport,
  buildAiToolAdaptersRunReport: runtime.buildAiToolAdaptersRunReport,
  buildAiToolAdaptersRunsReport: runtime.buildAiToolAdaptersRunsReport,
  buildAiToolAdaptersRunShowReport: runtime.buildAiToolAdaptersRunShowReport,
  buildAiToolAdaptersEnableExecutionReport: runtime.buildAiToolAdaptersEnableExecutionReport,
  buildAiToolAdaptersDisableExecutionReport: runtime.buildAiToolAdaptersDisableExecutionReport,
  buildAiToolAdaptersDashboardReport: runtime.buildAiToolAdaptersDashboardReport,
  buildAiToolAdaptersReadinessReport: runtime.buildAiToolAdaptersReadinessReport,
  buildAiToolAdaptersEvidenceReport: runtime.buildAiToolAdaptersEvidenceReport,
  buildAiToolAdaptersAuditReport: runtime.buildAiToolAdaptersAuditReport,
  scanKnownTools: runtime.scanKnownTools,
  resolveExecutableOnPath: runtime.resolveExecutableOnPath
};
