const fs = require("fs");
const path = require("path");
const { repoRoot } = require("../../../../src/cli/fs_utils");
const { resolveTrack } = require("../core/track_resolver");
const { pluginFolderError } = require("../core/errors");
const { ensureDir, writeFileIfMissing } = require("../utils/fs_safe");

function getAuditPaths(track, slug) {
  if (track === "owner") {
    return {
      logMd: path.join(repoRoot(), "plugins", slug, "docs", "AUDIT.md"),
      logJsonl: null,
      evidencePath: `./plugins/${slug}/docs/AUDIT.md`
    };
  }
  const root = path.join(repoRoot(), "workspaces", "plugins", slug, "10_plugin_evidence_audit");
  return {
    logMd: path.join(root, "audit_log.md"),
    logJsonl: path.join(root, "audit_log.jsonl"),
    evidencePath: `./workspaces/plugins/${slug}/10_plugin_evidence_audit/audit_log.jsonl`
  };
}

function buildAuditEvent(context = {}, previousStatus = "unknown", newStatus = "unknown", filesChanged = []) {
  const track = resolveTrack(context);
  const slug = context.plugin_slug || context.value || context.rest[0];
  if (!slug) throw pluginFolderError("Missing plugin slug.");
  if (track === "viber") throw pluginFolderError("Viber/App Track cannot create plugins directly. Switch to Plugin Development Track.");
  const paths = getAuditPaths(track, slug);
  const event = {
    event_id: `audit-${Date.now()}`,
    timestamp: new Date().toISOString(),
    actor_track: track,
    command: "plugin-folder audit",
    plugin_slug: slug,
    previous_status: previousStatus,
    new_status: newStatus,
    files_changed: Array.isArray(filesChanged) ? filesChanged : [],
    evidence_path: paths.evidencePath,
    result: "recorded",
    notes: "Generated by plugin_folder_structure audit service"
  };
  return { event, paths, track, slug };
}

function appendJsonl(filePath, record) {
  ensureDir(path.dirname(filePath));
  fs.appendFileSync(filePath, `${JSON.stringify(record)}\n`, "utf8");
}

function runAuditCommand(context) {
  const { event, paths, track, slug } = buildAuditEvent(context, "unknown", "recorded", []);
  ensureDir(path.dirname(paths.logMd));
  writeFileIfMissing(paths.logMd, "# Audit log\n");
  if (paths.logJsonl) appendJsonl(paths.logJsonl, event);
  if (context.flags && context.flags.json) console.log(JSON.stringify({ report_type: "plugin_folder_structure_audit", status: "recorded", track, slug, event }, null, 2));
  else console.log(`plugin-folder audit recorded for ${slug}`);
  return { report_type: "plugin_folder_structure_audit", status: "recorded", track, slug, event };
}

module.exports = {
  buildAuditEvent,
  runAuditCommand
};
